version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-3.6-mpich
      - test-3.6-openmpi
      - test-3.7-mpich
      - test-3.7-openmpi
      - test-3.8-mpich
      - test-3.8-openmpi

default-job: &default-job
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
    - run:
        name: Install dependencies in base environment
        command: conda env update -n base -f ${ENV_FILE}
    - run:
        name: List packages in the current environment (base)
        command: conda list
    - run:
        name: Running tests
        command: pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
    - run:
        name: Uploading code coverage report
        command: codecov
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports
    - save_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/opt/conda/pkgs"

jobs:

  test-3.6-mpich:
    <<: *default-job
    docker:
      - image: ncarxdev/miniconda:3.6
    environment:
      ENV_FILE: ".circleci/env-mpich.yml"

  test-3.6-openmpi:
    <<: *default-job
    docker:
      - image: ncarxdev/miniconda:3.6
    environment:
      ENV_FILE: ".circleci/env-openmpi.yml"
      MPIRICAL_MPIRUN: "mpirun --allow-run-as-root"
      OMPI_MCA_rmaps_base_oversubscribe: "1"

  test-3.7-mpich:
    <<: *default-job
    docker:
      - image: ncarxdev/miniconda:3.7
    environment:
      ENV_FILE: ".circleci/env-mpich.yml"

  test-3.7-openmpi:
    <<: *default-job
    docker:
      - image: ncarxdev/miniconda:3.7
    environment:
      ENV_FILE: ".circleci/env-openmpi.yml"
      MPIRICAL_MPIRUN: "mpirun --allow-run-as-root"
      OMPI_MCA_rmaps_base_oversubscribe: "1"

  test-3.8-mpich:
    <<: *default-job
    docker:
      - image: ncarxdev/miniconda:3.8
    environment:
      ENV_FILE: ".circleci/env-3.8-mpich.yml"

  test-3.8-openmpi:
    <<: *default-job
    docker:
      - image: ncarxdev/miniconda:3.8
    environment:
      ENV_FILE: ".circleci/env-openmpi.yml"
      MPIRICAL_MPIRUN: "mpirun --allow-run-as-root"
      OMPI_MCA_rmaps_base_oversubscribe: "1"

